### ISSUE TITLE
How to setup the dependiencies

### ISSUE THREAD

**Issue by georgeftakla** [oxpeter/datacatalog#4]
Hi oxpeter, 
Trying to run your interesting project. I followed the installation directions and installed packages for 
Django
django-autocomplete-light
django-bootstrap4
django-crispy-forms
numpy
psycopg

I got an error running python manage.py migrate... since persons.models does not exist. Then I added your Persons app folder to the same Django project and added line "'persons.apps.PersonsConfig' to INSTALLED_APPS in the Django's settings.py

I am not sure if this is the correct way to setup/install the project and its dependencies since I get "django.db.migrations.exceptions.NodeNotFoundError: Migration datacatalog.0001_initial dependencies reference nonexistent parent node ('dc_management', '0052_auto_20190118_1639')" when I run python manage.py migrate ... after adding persons

**Comment by oxpeter** [comment]
Hi @georgeftakla, 
This looks like the original database had a built-in dependency from a different app that is not required. The solution here is outlined well with this [StackOverflow solution](https://stackoverflow.com/questions/44489342/uninstall-app-a-that-app-b-have-a-dependency-in-one-old-migration): In short, 

- Go to your migrations/ folder and delete everything except the __init__.py file.
- Delete your app from the INSTALLED_APPS.
- Run python manage.py makemigrations which will recreate your migrations in the folder.
- Run python manage.py migrate

Because I will need to consider how modifications to the migrations directory will impact existing production servers, it will be a slow and careful effort before I can push a permanent fix to the codebase.

**Comment by oxpeter** [comment]
migration issue has now been fixed with [commit 7fef1da](https://github.com/oxpeter/datacatalog/commit/7fef1dac355d4e07b888b467fc494101b322af51), so users will not have to install datacore_web_managment app. Closing issue.
