### ISSUE TITLE
cannot find base.html

### ISSUE THREAD

**Issue by cybertian** [oxpeter/datacatalog#5]
hi Oxpeter,  base.html doesn't exist in the template folder, could u please take a look? thx

**Comment by oxpeter** [comment]
hi cybertian, datacatalog was written to utilise a user's existing base.html template, allowing the app to be an extension to an existing web project, rather than having to be standalone. You can create your own base.html template and add it to the root templates directory for the project. The only features that base.html will need to work with datacatalog are the following two blocks:

{% block navblock %}{% endblock %}
{% block content %}{% endblock %}

since you already closed this I hope it means you created your own workaround. Posting this here for anyone else looking for an answer. I'll also update the README instructions.

**Comment by oxpeter** [comment]
Updated with commit [af4c518](https://github.com/oxpeter/datacatalog/commit/af4c5182dd7740e224c820fc9dd92d626c1e357e)
